include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    #deprecated_member_use: ignore
    avoid_print: ignore
    unused_local_variable: ignore ignore

linter:
  rules:
    avoid_print: false
